name: Docker Image CI

on:
  push:
    branches:
      - main
  # You can customize this to trigger the workflow on pull requests or other events

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      run: docker login registry.example.com -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_ACCESS_TOKEN }}

    - name: Build Docker image
      run: docker build -t rampantspark/rampant.ide:latest .
      
    - name: Push Docker image
      run: docker push rampantspark/rampant.ide:latest
